/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGamesRouteImport } from './routes/admin/games'
import { Route as AdminGamesIndexRouteImport } from './routes/admin/games.index'
import { Route as AdminGamesGameIdTablesRouteImport } from './routes/admin/games.$gameId.tables'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesIndexRoute = AdminGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGamesRoute,
} as any)
const AdminGamesGameIdTablesRoute = AdminGamesGameIdTablesRouteImport.update({
  id: '/$gameId/tables',
  path: '/$gameId/tables',
  getParentRoute: () => AdminGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/games/$gameId/tables': typeof AdminGamesGameIdTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/games': typeof AdminGamesIndexRoute
  '/admin/games/$gameId/tables': typeof AdminGamesGameIdTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/admin/games/$gameId/tables': typeof AdminGamesGameIdTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/games'
    | '/admin/'
    | '/admin/games/'
    | '/admin/games/$gameId/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/games' | '/admin/games/$gameId/tables'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/games'
    | '/admin/'
    | '/admin/games/'
    | '/admin/games/$gameId/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games/': {
      id: '/admin/games/'
      path: '/'
      fullPath: '/admin/games/'
      preLoaderRoute: typeof AdminGamesIndexRouteImport
      parentRoute: typeof AdminGamesRoute
    }
    '/admin/games/$gameId/tables': {
      id: '/admin/games/$gameId/tables'
      path: '/$gameId/tables'
      fullPath: '/admin/games/$gameId/tables'
      preLoaderRoute: typeof AdminGamesGameIdTablesRouteImport
      parentRoute: typeof AdminGamesRoute
    }
  }
}

interface AdminGamesRouteChildren {
  AdminGamesIndexRoute: typeof AdminGamesIndexRoute
  AdminGamesGameIdTablesRoute: typeof AdminGamesGameIdTablesRoute
}

const AdminGamesRouteChildren: AdminGamesRouteChildren = {
  AdminGamesIndexRoute: AdminGamesIndexRoute,
  AdminGamesGameIdTablesRoute: AdminGamesGameIdTablesRoute,
}

const AdminGamesRouteWithChildren = AdminGamesRoute._addFileChildren(
  AdminGamesRouteChildren,
)

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
